### ISSUE TITLE
Null values serialization

### ISSUE THREAD

**Issue by dmitriy-barkalov** [nicklebedev37/autorest#1]
Null values should not be added to JSON representation of request model. At least for Azure.Ruby generator

Steps to reproduce:
1. Generate ResourceManagement SDK
2. Try to perform Resource group creation

```
    params = Models::ResourceGroup.new()
    params.location = 'West US'
    params.tags = { 'tag1' => 'val1', 'tag2' => 'val2' }

    result = subject.resource_groups.create_or_update(resource_group_name, params).value!
    expect(result.response).to be_an_instance_of(Net::HTTPOK)
```

Expected:
Resource group added

Actual:
HTTP 400 error. With message "The request content was invalid and could not be deserialized: 'Could not find member 'provisioningState' on object of type 'ResourceGroupDefinition'. Path 'provisioningState', line 1, position 97"

**Comment by nicklebedev37** [comment]
Done at 933e7d4722ffe94f3fcfa9ea601603a1efbd8a9e
I believe it is already worked since resource SDK methods mentioned above have worked.
