### ISSUE TITLE
x-ms-external resources results in wrong namespace

### ISSUE THREAD

**Issue by dmitriy-barkalov** [nicklebedev37/autorest#9]
Steps to reproduce:
1 Generate Compute SDK from https://github.com/Azure/azure-rest-api-specs/blob/master/arm-compute/2015-06-15/swagger/compute.json

Expected:
https://github.com/dmitriy-barkalov/azure-sdk-for-ruby/blob/feature/arm-sdk-pr/lib/azure/arm/ComputeManagement/lib/azure_compute_management/Models/virtual_machine_properties.rb#L82 has MsRestAzure namespace

Actual:
Internal SDK namespace

**Comment by nicklebedev37** [comment]
Done at 38234f9394a2aecbecde286f191bead5bf074400

**Comment by nicklebedev37** [comment]
Totally reworked the feature, don't use namespace anymore - now just included modules where required 04bcd2e0ee437f929d03759b5d0b985a2a1fd92c
